[colors.bright]
black = "#41505e"
blue = "#5ec4ff"
cyan = "#70e1e8"
green = "#8bd49c"
magenta = "#e27e8d"
red = "#d95468"
white = "#ffffff"
yellow = "#ebbf83"

[colors.cursor]
cursor = "#ffffff"
text = "#171d23"

[colors.normal]
black = "#333f4a"
blue = "#539afc"
cyan = "#70e1e8"
green = "#8bd49c"
magenta = "#b62d65"
red = "#d95468"
white = "#b7c5d3"

[colors.primary]
background = "#171d23"
foreground = "#ffffff"

[font]
size = 7

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
opacity = 0.6

[window.padding]
x = 15
y = 15
